name: Build and Deploy backend services
run-name: Building ${{ github.event.inputs.service }} from ${{ github.ref_name }}

on: 
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: Choose environment
        options: 
        - qa-aut
        - qa-int
        - ld-staging
        - player-test
        - au-qa
        - au-uat
        - test-a
        - cci-staging
        - app-staging
        - xnl-training
      user:
        type: choice
        description: Choose user
        options: 
        - automation-test
        - internal-1
        - internal-2
        - internal-3
        - marija@gmail.com

jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print chosen variables
        run: |
          echo "Chosen environment: ${{ github.event.inputs.service }}"
          echo "Chosen user: ${{ github.event.inputs.user }}"
          echo "AT Username ${{ secrets.AUTOMATION_TEST_USERNAME }}"
          echo "At Password ${{ secrets.AUTOMATION_TEST_PASSWORD }}"
          echo "AT Username ${{ secrets.AUTOMATION_TEST_PASSWORD }}" > secret_value.txt



          case "${{ github.event.inputs.user }}" in
                  "automation-test")
              echo "inside automation test case"
              # Set new environment variables
              echo "SELECTED_USERNAME=${{ secrets.AUTOMATION_TEST_USERNAME }}" >> $GITHUB_ENV
              echo "SELECTED_PASSWORD=${{ secrets.AUTOMATION_TEST_PASSWORD }}" >> $GITHUB_ENV
            ;;
            
                "internal-1")
              echo "inside internal-1 test case"
              # Set new environment variables
              echo "SELECTED_USERNAME=${{ secrets.INTERNAL_1_USERNAME }}" >> $GITHUB_ENV
              echo "SELECTED_PASSWORD=${{ secrets.INTERNAL_1_PASSWORD }}" >> $GITHUB_ENV
            ;;
            esac
          
          # Print the newly created environment variables
          echo "SELECTED_USERNAME: $SELECTED_USERNAME"
          echo "SELECTED_PASSWORD: $SELECTED_PASSWORD"
      - name: Display secret value
        run: cat secret_value.txt
          
